// AetherVM - Lift. Instrument. Emulate. Recover.
// Copyright (c) 2026 Jesse Liu <neoliu2011@gmail.com>
// SPDX-License-Identifier: Apache License, Version 2.0
// See LICENSE file in the root directory for full license text.

#include <icpp.hpp>

namespace {

void iterate_lines(const fs::path &infile,
                   const std::function<void(std::string_view line)> &callback) {
  std::ifstream file(infile, std::ios::binary);
  if (!file.is_open()) {
    std::println("Failed to open {}.", infile.string());
    return;
  }

  for (std::string line; std::getline(file, line); callback(line))
    ;
}

constexpr std::string_view trim_string(std::string_view sv) noexcept {
  auto is_not_space = [](unsigned char ch) { return !std::isspace(ch); };
  auto start = std::find_if(sv.begin(), sv.end(), is_not_space);
  auto end = std::find_if(sv.rbegin(), sv.rend(), is_not_space).base();
  return sv.substr(start - sv.begin(), end - start);
}

bool is_newer(const fs::path &file0, const fs::path &file1) {
  std::error_code ec;
  if (!fs::exists(file0, ec))
    return false;
  if (!fs::exists(file1, ec))
    return true;
  return fs::last_write_time(file0, ec) > fs::last_write_time(file1, ec);
}

void generate_handler(std::string_view remill, std::string_view arch,
                      std::string_view outsrc) {
  std::set<std::string> isels;
  auto sems = std::format("{}/lib/Arch/{}", remill, arch);
  std::println("Parsing {}...", sems);
  for (auto &entry : fs::recursive_directory_iterator(sems)) {
    if (entry.path().extension() == ".cpp")
      iterate_lines(entry.path(), [&isels](std::string_view line) {
        if (line.starts_with("DEF_ISEL")) {
          auto start = line.find('(') + 1;
          auto end = line.find(')');
          auto name = trim_string(line.substr(start, end - start));
          auto comma = name.find(',');
          if (comma == std::string_view::npos) {
            isels.insert(std::string(name));
          } else {
            auto nameprefix = std::string(name.substr(0, comma));
            for (auto bits : {"_8", "_16", "_32", "_64"})
              isels.insert(nameprefix + bits);
          }
        }
      });
  }
  std::string gencode{std::format(
      R"(// Auto-generated by AetherVM, DO NOT EDIT!

#include "../src/Handler.h"
#include <iterator>

#define UNSUPPORTED_INSTRUCTION UNSUPPORTED_INSTRUCTION_{0}
#define INVALID_INSTRUCTION INVALID_INSTRUCTION_{0}

)",
      arch)};
  for (auto &name : isels)
    gencode += std::format("ISEL_DECL({});\n", name);

  gencode += std::format(R"(
namespace aether {{
const HandlerRaw Handler{}[] = {{
)",
                         arch);

  for (auto &name : isels)
    gencode += std::format("\tISEL_RAW_ITEM({}),\n", name);

  gencode += std::format(R"(
}};
const size_t Handler{0}Num = std::size(Handler{0});
}})",
                         arch);

  std::ofstream outf(fs::path(outsrc), std::ios::binary);
  if (!outf.is_open()) {
    std::println("Failed to create {}.", outsrc);
    return;
  }
  outf.write(gencode.data(), gencode.size());
  std::println("Created {}.", outsrc);
}

} // namespace

int main(int argc, const char *argv[]) {
  if (argc != 3) {
    std::println("Usage: {} /path/to/remill /path/to/generated", argv[0]);
    return -1;
  }
  for (auto arch : {"AArch64", "X86"}) {
    auto outsrc = std::format("{}/Handler{}.cpp", argv[2], arch);
    if (is_newer(outsrc, argv[0]))
      std::println("{} is up to update.", outsrc);
    else
      generate_handler(argv[1], arch, outsrc);
  }
  return 0;
}
