// AetherVM - Lift. Instrument. Emulate. Recover.
// Copyright (c) 2026 Jesse Liu <neoliu2011@gmail.com>
// SPDX-License-Identifier: Apache License, Version 2.0
// See LICENSE file in the root directory for full license text.

#include <cstdlib>

#define UNDEF_ISEL(n)                                                          \
  static void _##n(void) { abort(); }                                          \
  extern "C" void (*ISEL_##n)(void) = _##n

UNDEF_ISEL(BOUND_GPRv_MEMa16_16);

UNDEF_ISEL(BOUND_GPRv_MEMa32_32);

UNDEF_ISEL(CALL_NEAR_RELBRd_16);

UNDEF_ISEL(CALL_NEAR_RELBRd_32);

UNDEF_ISEL(CALL_NEAR_RELBRd_8);

UNDEF_ISEL(CALL_NEAR_RELBRz_16);

UNDEF_ISEL(CALL_NEAR_RELBRz_32);

UNDEF_ISEL(CALL_NEAR_RELBRz_8);

UNDEF_ISEL(INTO);

UNDEF_ISEL(IRETD_32);

UNDEF_ISEL(JMP_FAR_PTRp_IMMw_16);

UNDEF_ISEL(JMP_FAR_PTRp_IMMw_32);

UNDEF_ISEL(JMP_GPRv_16);

UNDEF_ISEL(JMP_GPRv_32);

UNDEF_ISEL(JMP_MEMv_16);

UNDEF_ISEL(JMP_MEMv_32);

UNDEF_ISEL(JMP_RELBRz_16);

UNDEF_ISEL(JMP_RELBRz_32);

UNDEF_ISEL(JMP_RELBRz_8);

UNDEF_ISEL(LEAVE_32);

UNDEF_ISEL(LEAVE_8);

UNDEF_ISEL(POPAD_32);

UNDEF_ISEL(POPA_32);

UNDEF_ISEL(POPFD);

UNDEF_ISEL(POP_DS_32);

UNDEF_ISEL(POP_ES_32);

UNDEF_ISEL(POP_FS_32);

UNDEF_ISEL(POP_GPRv_51_32);

UNDEF_ISEL(POP_GPRv_51_8);

UNDEF_ISEL(POP_GPRv_58_32);

UNDEF_ISEL(POP_GPRv_58_8);

UNDEF_ISEL(POP_GPRv_8F_32);

UNDEF_ISEL(POP_GPRv_8F_8);

UNDEF_ISEL(POP_GS_32);

UNDEF_ISEL(POP_MEM_XSP_32);

UNDEF_ISEL(POP_MEM_XSP_8);

UNDEF_ISEL(POP_MEMv_32);

UNDEF_ISEL(POP_MEMv_8);

UNDEF_ISEL(POP_SS_32);

UNDEF_ISEL(PUSHAD_32);

UNDEF_ISEL(PUSHA_16);

UNDEF_ISEL(PUSHFD);

UNDEF_ISEL(PUSH_GPRv_50_32);

UNDEF_ISEL(PUSH_GPRv_50_8);

UNDEF_ISEL(PUSH_GPRv_FFr6_32);

UNDEF_ISEL(PUSH_GPRv_FFr6_8);

UNDEF_ISEL(PUSH_IMMb_32);

UNDEF_ISEL(PUSH_IMMb_8);

UNDEF_ISEL(PUSH_IMMz_32);

UNDEF_ISEL(PUSH_IMMz_8);

UNDEF_ISEL(PUSH_MEMv_32);

UNDEF_ISEL(PUSH_MEMv_8);

UNDEF_ISEL(RET_NEAR_16);

UNDEF_ISEL(RET_NEAR_32);

UNDEF_ISEL(RET_NEAR_8);

UNDEF_ISEL(RET_NEAR_IMMw_16);

UNDEF_ISEL(RET_NEAR_IMMw_32);

UNDEF_ISEL(RET_NEAR_IMMw_8);
